openapi: 3.0.1
info:
  title: API / Deliverers
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: deliverers
    description: ''
paths:
  /deliverers:
    get:
      tags:
        - deliverers
      summary: Pobiera listę dostawców
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deliverer'
  /deliverers/{deliverer-uuid}:
    get:
      tags:
        - deliverers
      summary: Pobiera dostawcę
      parameters:
        - name: deliverer-uuid
          in: path
          description: UUID pobieranego dostawcy
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deliverer'
        '404':
          description: Nie istnieje
          content: {}
    put:
      tags:
        - deliverers
      summary: Nadpisuje dostawcę
      parameters:
        - name: deliverer-uuid
          in: path
          description: UUID pobieranego dostawcy
          required: true
          schema:
            type: string
            format: UUID
      requestBody:
        description: Uaktualniany lub wstawiany dostawca
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deliverer'
        required: true
      responses:
        '200':
          description: OK
          content: {}
        '400':
          description: Błąd walidacji
          content: {}
    delete:
      tags:
        - deliverers
      summary: Usuwa dostawcę
      parameters:
        - name: deliverer-uuid
          in: path
          description: UUID usuwanego dostawcy
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: OK
          content: {}
components:
  schemas:
    Deliverer:
      type: object
      properties:
        uuid:
          type: string
          format: UUID
        personalData:
          $ref: '#/components/schemas/PersonalData'
        logginData:
          $ref: '#/components/schemas/LogginData'
        archive:
          type: string
          enum: ["CURRENT", "ARCHIVE"]
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
    PersonalData:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        sex:
          type: string
          enum: [MALE, FEMALE, OTHER]
        phone:
          type: string
        email:
          type: string
    LogginData:
      type: object
      properties:
        login:
          type: string
    Order:
      type: object
      properties:
        uuid:
          type: string
          format: UUID