openapi: 3.0.1
info:
  title: API / Dishes
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: dishes
    description: ''
paths:
  /dishes:
    get:
      tags:
        - dishes
      summary: Pobiera listę dań
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
  /dishes/{dish-uuid}:
    get:
      tags:
        - dishes
      summary: Pobiera danie
      parameters:
        - name: dish-uuid
          in: path
          description: UUID pobieranego dania
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '404':
          description: Not found
          content: {}
    put:
      tags:
        - dishes
      summary: Dodawanie lub nadpisywanie dania
      parameters:
        - name: dish-uuid
          in: path
          description: UUID pobieranego dania
          required: true
          schema:
            type: string
            format: UUID
      requestBody:
        description: Uaktualnienie lub wstawienie dania
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dish'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '400':
          description: Validation error
          content: { }
    delete:
      tags:
        - dishes
      summary: Usuwa dane
      parameters:
        - name: dish-uuid
          in: path
          description: UUID pobieranego dania
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dish'
        '404':
          description: Not found
          content: { }
components:
  schemas:
    Dish:
      type: object
      properties:
        uuid:
          type: string
          format: UUID
        quantity:
          type: integer
          minimum: 0
        product:
          $ref: '#/components/schemas/Product'
        menuItems:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
          readOnly: true
    Product:
      type: object
      properties:
        uuid:
          type: string
          format: UUID
    MenuItem:
      type: object
      properties:
        uuid:
          type: string
          format: UUID